window.ABIGAIL_PROJECTS = [
  {
      id: "uncommon-grace",
      title: "Roll Up Mag #66 vol.1",
      category: "editorial",
      categoryLabel: "Editorial",
      year: "JULY 2026",
      client: "Roll Up Magazine",
      description: "(un)casual wardrobe, July 2026",
      concept: "",
      credits: {
    "Styling & AD": "Abigail Diantete",
    "Photographer": "Matthieu Gorin",
    "MUA & Hairstylist": "Asma Nafati",
    "Models": "Nils Foulon & Mila Chistiakova"},
      images: ["assets/images/editorial/roll-up-mag/uncommon-grace-01.jpg", "assets/images/editorial/roll-up-mag/uncommon-grace-02.jpg", "assets/images/editorial/roll-up-mag/uncommon-grace-03.jpg" ,  "assets/images/editorial/roll-up-mag/4.jpg",  "assets/images/editorial/roll-up-mag/5.jpg", "assets/images/editorial/roll-up-mag/6.jpg", "assets/images/editorial/roll-up-mag/7.jpg", "assets/images/editorial/roll-up-mag/8.jpg"]
    },
  {
      id: "in-transit",
      title: "S&M Magazine Issue 3",
      category: "editorial",
      categoryLabel: "Editorial",
      year: "JUNE 2026",
      client: "S&M Magazine Issue 3",
      description: "CRASH",
      concept: "",
      credits: {
    "Photographer": "Rebecca Dorothy",
    "Stylist": "Martina Bruna",
    "Stylist Assistant": "Abigail Diantete",
    "Make-Up": "Roscino Makeup",
    "Hair": "Romain Duplessy",
    "Casting": "Elisa Villa & Millemila Baci",
    "Models": "Juliaryan Murray & Valya Fedotova — Supreme Management" },
      images: ["assets/images/editorial/crash-s&m/in-transit-01.jpg", "assets/images/editorial/crash-s&m/in-transit-02.jpg", "assets/images/editorial/crash-s&m/in-transit-03.jpg" ,  "assets/images/editorial/crash-s&m/3.jpg",  "assets/images/editorial/crash-s&m/4.jpg" , "assets/images/editorial/crash-s&m/5.jpg" , "assets/images/editorial/crash-s&m/6.jpg" , "assets/images/editorial/crash-s&m/7.jpg" , "assets/images/editorial/crash-s&m/8.jpg" , "assets/images/editorial/crash-s&m/9.jpg" , "assets/images/editorial/crash-s&m/10.jpg" , "assets/images/editorial/crash-s&m/11.jpg"]
    },
  {
      id: "maya-k",
      title: "LES FLAMMES CEREMONY",
      category: "talents",
      categoryLabel: "Talents",
      year: "APRIL 2026",
      client: "Artist Portrait",
      description: "Styling work with Vanityprojects Corp for Les Flammes Ceremony",
      concept: "",
      credits: {"Hosts team": "Newin Bokhari, Darryl Gm & Driver mc",
      "In collaboration with": "Yard" },
      images: ["assets/images/talents/maya-k-01.jpg", "assets/images/talents/maya-k-02.jpg", "assets/images/talents/maya-k-03.jpg", "assets/images/talents/4.jpg", "assets/images/talents/5.jpg"]
    },
  {
      id: "family-archive",
      title: "Personal fashion project (3)",
      category: "personal",
      categoryLabel: "Personal Projects",
      year: "APRIL 2026",
      client: "Personal Project",
      description: "",
      concept: "",
      credits: {
    "Photographer": "Prosper Panhard",
    "Stylist": "Abigail Diantete",
    "Model": "Atmane Yousfi — Next Paris"},
      images: ["assets/images/personal/26_03-propser-panhard/9.jpg", "assets/images/personal/26_03-propser-panhard/family-archive-01.jpg", "assets/images/personal/26_03-propser-panhard/family-archive-02.jpg", "assets/images/personal/26_03-propser-panhard/family-archive-03.jpg", "assets/images/personal/26_03-propser-panhard/4.jpg", "assets/images/personal/26_03-propser-panhard/5.jpg", "assets/images/personal/26_03-propser-panhard/6.jpg", "assets/images/personal/26_03-propser-panhard/7.jpg", "assets/images/personal/26_03-propser-panhard/8.jpg"]
    },
  {
      id: "soft-armour",
      title: "F*CKING YOUNG! ONLINE",
      category: "editorial",
      categoryLabel: "Editorial",
      year: "FEBRUARY 2026",
      client: "Fucking Young!",
      description: "",
      concept: "",
      credits: {
    "Talent": "Giovani Zattera",
    "Photographer": "Rebecca Dorothy",
    "Stylist": "Martina Bruna",
    "Stylist Assistant": "Abigail Diantete",
    "MUA": "Takako",
    "Photography Assistants": "Thomas Makhlouf & Mathilde Bono",
    "Interview": "Anna Rose Barr" },
      images: ["assets/images/editorial/giovanni-x-fy/soft-armour-01.jpg", "assets/images/editorial/giovanni-x-fy/soft-armour-02.jpg", "assets/images/editorial/giovanni-x-fy/soft-armour-03.jpg", "assets/images/editorial/giovanni-x-fy/4.jpg", "assets/images/editorial/giovanni-x-fy/5.jpg", "assets/images/editorial/giovanni-x-fy/6.jpg", "assets/images/editorial/giovanni-x-fy/7.jpg", "assets/images/editorial/giovanni-x-fy/8.jpg", "assets/images/editorial/giovanni-x-fy/9.jpg", "assets/images/editorial/giovanni-x-fy/10.jpg"]
    },
  {
      id: "blue-room",
      title: "Test Shoot Project",
      category: "personal",
      categoryLabel: "Personal Projects",
      year: "FEBRUARY 2026",
      client: "Personal Project",
      description: "",
      concept: "",
      credits: { 
    "Photographer": "Luigi Cianfarano",
    "Stylist": "Martina Bruna",
    "Stylist Assistant": "Abigail Diantete",
    "HMU": "Raphaële Parot",
    "Model": "Eduarda Bretas — IMG Paris"},
      images: ["assets/images/personal/SHOOT-LUIGI/blue-room-01.jpg", "assets/images/personal/SHOOT-LUIGI/blue-room-02.jpg", "assets/images/personal/SHOOT-LUIGI/blue-room-03.jpg", "assets/images/personal/SHOOT-LUIGI/4.jpg", "assets/images/personal/SHOOT-LUIGI/5.jpg", "assets/images/personal/SHOOT-LUIGI/6.jpg", "assets/images/personal/SHOOT-LUIGI/7.jpg", "assets/images/personal/SHOOT-LUIGI/8.jpg"]
    },
  {
      id: "personal-fashion-project-2",
      title: "Personal fashion project (2)",
      category: "personal",
      categoryLabel: "personal",
      year: " DECEMBER 2025",
      client: "",
      description: "",
      concept: "",
      credits: {
  "Photographer": "Laetitia Prioux",
  "Stylist": "Abigail Diantete",
  "Models": "Joshua Zijdeman - Next Paris"
  },
      images: ["assets/images/personal/Personal-project/1.jpg","assets/images/personal/Personal-project/2.jpg","assets/images/personal/Personal-project/3.jpg","assets/images/personal/Personal-project/4.jpg"]
    },
  {
      id: "sunday-uniform",
      title: "Personal fashion project (1)",
      category: "personal",
      categoryLabel: "Personal Projects",
      year: "DECEMBER 2025",
      client: "Personal Project",
      description: "",
      concept: "",
      credits: {
    "Photographer": "Ria Mort",
    "Stylist": "Abigail Diantete",
    "Makeup": "Thomas Kergot",
    "Model": "Rui Wang — Next Paris"
  },
      images: ["assets/images/personal/SHOOT-RIA/sunday-uniform-01.jpg", "assets/images/personal/SHOOT-RIA/sunday-uniform-02.jpg", "assets/images/personal/SHOOT-RIA/sunday-uniform-03.jpg", "assets/images/personal/SHOOT-RIA/4.jpg", "assets/images/personal/SHOOT-RIA/5.jpg", "assets/images/personal/SHOOT-RIA/6.jpg"]
    },
  {
      id: "second-skin",
      title: "FGUK Magazine Online",
      category: "editorial",
      categoryLabel: "Editorial",
      year: "OCTOBER 2025",
      client: "FGUK Magazine Online",
      description: "Epicure",
      concept: "",
      credits: {
    "Photographer": "Aubane Després",
    "Styling": "Martina Bruna",
    "Pastry Chef": "Florian Mongaï",
    "Video DOP / Edit / Color": "Anthony Peyper",
    "Set Designer": "Agathe Reille Soult",
    "Stylist Assistants": "Emma Moulay & Abigail Diantete",
    "Photographer Assistant": "Marine Brilloit",
    "Video Assistant": "Vicktor Podcacha",
    "Model": "Sarang Cheoung / Urban Models Management",
    "Make-Up Artist": "Mathilde Gasparini",
    "Hair Stylist": "Stef Worldhair"},
      images: ["assets/images/editorial/epicure/second-skin-01.jpg", "assets/images/editorial/epicure/second-skin-02.jpg", "assets/images/editorial/epicure/second-skin-03.jpg", "assets/images/editorial/epicure/4.jpg", "assets/images/editorial/epicure/5.jpg", "assets/images/editorial/epicure/6.jpg", "assets/images/editorial/epicure/7.jpg", "assets/images/editorial/epicure/8.jpg"],
      videos : [ "assets/videos/epicure-video.mp4"]
    },
  {
      id: "after-hours",
      title: "WARDROBE WARS",
      category: "editorial",
      categoryLabel: "Editorial",
      year: "2025",
      client: "Schema Magazine",
      description: "",
      concept: "",
      credits: {
    "Photographer": "Lebon Bourgeois @lebonbourgeois",
    "EIC": "Sara Bastai @sarabastai",
    "Artistic Direction": "Sylvia Perez @sylvia_perezperez",
    "Stylist": "Julianne Courtois @juliannecourtois",
    "Make-Up Artist": "Kamila Vay @kamilavay",
    "Hair Stylist": "Rimi Ura @rimiura",
    "Set Designer": "Milena Krastev @milenakrastev",
    "Nail Artist": "Delphine Aissi @delphineaissi",
    "Light Assistant": "Baptiste Zysman @baptiste_zysman",
    "Stylist Assistant": "Abigail Diantete",
    "Special Thanks": "Thomas Manil @thomas_manil"},
      images: ["assets/images/editorial/shema-magazine/after-hours-01.jpg", "assets/images/editorial/shema-magazine/after-hours-02.jpg", "assets/images/editorial/shema-magazine/after-hours-03.jpg" , "assets/images/editorial/shema-magazine/after-hours-04.jpg" , "assets/images/editorial/shema-magazine/after-hours-05.jpg" , "assets/images/editorial/shema-magazine/after-hours-06.jpg"]
    },
  {
      id: "objects-in-motion",
      title: "BOTH PARIS",
      category: "campaign",
      categoryLabel: "Campaign",
      year: " (le mois ??)2025",
      client: "BOTH PARIS",
      description: "Spring Campaign (2025)",
      concept: "",
      credits: { 
    "Photographer": "Elliott SB",
    "Stylist": "Abigail Diantete",
    "HMU": "Leah Bedfert",
    "Production Coordinator": "Camille Badée" },
      images: ["assets/images/campaign/BOTH/objects-in-motion-01.jpg", "assets/images/campaign/BOTH/objects-in-motion-02.jpg", "assets/images/campaign/BOTH/objects-in-motion-03.jpg", "assets/images/campaign/BOTH/4.jpg", "assets/images/campaign/BOTH/5.jpg", "assets/images/campaign/BOTH/6.jpg", "assets/images/campaign/BOTH/7.jpg"]
    },
  {
      id: "parisian-playground",
      title: "PARISIAN PLAYGROUND - LVMH PRIZE x 24S",
      category: "campaign",
      categoryLabel: "Campaign",
      year: "2024",
      client: "LVMH PRIZE x 24S",
      description: "Capsule Collection (2024)",
      concept: "",
      credits: {
    "Brands": "Better — Setchu — Magliano",
    "Styling": "Manon Del Colle",
    "Styling Assistant": "Abigail Diantete",
    "Photography": "Gabriel Boyer",
    "Film Director": "Gabriel Mokayed",
    "Art Direction": "Aubéry Lambert",
    "Hair": "Charlotte Dubreuil Gourion",
    "MUA": "Loren Boss",
    "Model":"Teo Fortin (M Management), Jahika Gonzalez (Women 360) & Emily Liptow (Marilyn)",
    "Production": "Kartel Paris"},
      images: ["assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/1.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/2.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/3.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/4.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/5.jpg", "assets/images/campaign/CAPSULE-LVMH-PRIZE_2023/6.jpg"]
    },
  {
      id: "common-ground",
      title: "24S X COPERNI",
      category: "campaign",
      categoryLabel: "Campaign",
      year: " (MOIS ?) 2023",
      client: "24S",
      description: "Capsule Collection (2023)",
      concept: "",
      credits: {
    "Talent": "Alanna Archibald — Marilyn Agency Paris",
    "Styling": "Manon Del Colle",
    "Styling assistant": "Abigail Diantete",
    "Photography": "Studio L'Étiquette",
    "Art Direction": "Aubéry Lambert",
    "Set Design": "Julien Cavallina",
    "Hair & Makeup": "Aurore Gibrien",
    "Production": "Yanis Bezine" },
      images: ["assets/images/campaign/24SxCoperni/common-ground-01.jpg", "assets/images/campaign/24SxCoperni/common-ground-02.jpg", "assets/images/campaign/24SxCoperni/common-ground-03.jpg", "assets/images/campaign/24SxCoperni/4.jpg", "assets/images/campaign/24SxCoperni/5.jpg", "assets/images/campaign/24SxCoperni/6.jpg"]
    }
];
